name: Auto Tweet Using AI

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      
      - name: Install & Update Dependencies
        run: |
          npm install
          npm install @google/generative-ai@latest --save-exact
          # Verify correct version
          npm list @google/generative-ai
      
      - name: Run Bot
        run: npm start
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
